name: bootstrap-spring-boot
services:
  app:
    container_name: bootstrap-spring-boot-app
    image: bootstrap-spring-boot
    ports:
      - 80:8080
    depends_on:
      - db
    command: java -jar /app/app.jar
  db:
    container_name: bootstrap-spring-boot-db
    image: mysql
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_USER=myuser
    ports:
      - 3306:3306